#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Erp")]
public partial class DataLayerExperienceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertEntreprise(Entreprise instance);
  partial void UpdateEntreprise(Entreprise instance);
  partial void DeleteEntreprise(Entreprise instance);
  partial void InsertNomenclature_Contact(Nomenclature_Contact instance);
  partial void UpdateNomenclature_Contact(Nomenclature_Contact instance);
  partial void DeleteNomenclature_Contact(Nomenclature_Contact instance);
  partial void InsertUtilisateur(Utilisateur instance);
  partial void UpdateUtilisateur(Utilisateur instance);
  partial void DeleteUtilisateur(Utilisateur instance);
  partial void InsertAttribut_Evenement(Attribut_Evenement instance);
  partial void UpdateAttribut_Evenement(Attribut_Evenement instance);
  partial void DeleteAttribut_Evenement(Attribut_Evenement instance);
  partial void InsertNomenclature_Evenement(Nomenclature_Evenement instance);
  partial void UpdateNomenclature_Evenement(Nomenclature_Evenement instance);
  partial void DeleteNomenclature_Evenement(Nomenclature_Evenement instance);
  #endregion
	
	public DataLayerExperienceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RessourceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Entreprise> Entreprise
	{
		get
		{
			return this.GetTable<Entreprise>();
		}
	}
	
	public System.Data.Linq.Table<Nomenclature_Contact> Nomenclature_Contacts
	{
		get
		{
			return this.GetTable<Nomenclature_Contact>();
		}
	}
	
	public System.Data.Linq.Table<Utilisateur> Utilisateur
	{
		get
		{
			return this.GetTable<Utilisateur>();
		}
	}
	
	public System.Data.Linq.Table<Attribut_Evenement> Attribut_Evenement
	{
		get
		{
			return this.GetTable<Attribut_Evenement>();
		}
	}
	
	public System.Data.Linq.Table<Nomenclature_Evenement> Nomenclature_Evenement
	{
		get
		{
			return this.GetTable<Nomenclature_Evenement>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CompteUtilisateur")]
	public ISingleResult<CompteUtilisateurResult> CompteUtilisateur()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<CompteUtilisateurResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertControleQualite")]
	public int InsertControleQualite(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDocument", DbType="NVarChar(MAX)")] string codeDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(MAX)")] string designation, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(MAX)")] string reference, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RQEP", DbType="NVarChar(MAX)")] string rQEP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DPCPE", DbType="NVarChar(MAX)")] string dPCPE, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DesignCoord", DbType="NVarChar(MAX)")] string designCoord, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PC", DbType="NVarChar(MAX)")] string pC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EL", DbType="NVarChar(MAX)")] string eL, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="INS", DbType="NVarChar(MAX)")] string iNS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MEPP", DbType="NVarChar(MAX)")] string mEPP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CV", DbType="NVarChar(MAX)")] string cV, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SF", DbType="NVarChar(MAX)")] string sF, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISPC", DbType="NVarChar(MAX)")] string iSPC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISELPRJS", DbType="NVarChar(MAX)")] string iSELPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISINSPRJS", DbType="NVarChar(MAX)")] string iSINSPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISMEPPPRJS", DbType="NVarChar(MAX)")] string iSMEPPPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISCVPRJS", DbType="NVarChar(MAX)")] string iSCVPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISSFPRJS", DbType="NVarChar(MAX)")] string iSSFPRJS, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLPC", DbType="NVarChar(MAX)")] string pSLPC, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLEL", DbType="NVarChar(MAX)")] string pSLEL, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLIN", DbType="NVarChar(MAX)")] string pSLIN, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLMEPP", DbType="NVarChar(MAX)")] string pSLMEPP, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLCV", DbType="NVarChar(MAX)")] string pSLCV, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PSLSF", DbType="NVarChar(MAX)")] string pSLSF, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLIENT", DbType="NVarChar(MAX)")] string cLIENT, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observation", DbType="NVarChar(MAX)")] string observation)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codeDocument, designation, reference, rQEP, dPCPE, designCoord, pC, eL, iNS, mEPP, cV, sF, iSPC, iSELPRJS, iSINSPRJS, iSMEPPPRJS, iSCVPRJS, iSSFPRJS, pSLPC, pSLEL, pSLIN, pSLMEPP, pSLCV, pSLSF, cLIENT, observation);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertDocumentEtude")]
	public int InsertDocumentEtude([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodeDocument", DbType="NVarChar(MAX)")] string codeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitreDocument", DbType="NVarChar(MAX)")] string titreDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rev", DbType="NVarChar(MAX)")] string rev, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Avancement", DbType="NVarChar(MAX)")] string avancement, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmissionPlanifiee", DbType="NVarChar(MAX)")] string emissionPlanifiee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApprobationPanifiee", DbType="NVarChar(MAX)")] string approbationPanifiee, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Poids", DbType="NVarChar(MAX)")] string poids, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ponderation", DbType="NVarChar(MAX)")] string ponderation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NBHIngenieur", DbType="NVarChar(MAX)")] string nBHIngenieur, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NBHProjeteur", DbType="NVarChar(MAX)")] string nBHProjeteur, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Etat", DbType="NVarChar(MAX)")] string etat)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, codeDocument, titreDocument, rev, avancement, emissionPlanifiee, approbationPanifiee, poids, ponderation, nBHIngenieur, nBHProjeteur, etat);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertDocEtudeETQualiteProjet")]
	public int InsertDocEtudeETQualiteProjet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matricume", DbType="NVarChar(MAX)")] string matricume, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewCodeDocument", DbType="NVarChar(MAX)")] string newCodeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OldCodeDocument", DbType="NVarChar(MAX)")] string oldCodeDocument, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewReference", DbType="NVarChar(MAX)")] string newReference)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricume, newCodeDocument, oldCodeDocument, newReference);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertDetailProjet")]
	public int insertDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idphace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idTypeProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string taskforce, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclasseProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Revision", DbType="NVarChar(MAX)")] string revision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DD", DbType="NVarChar(MAX)")] string dD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DF", DbType="NVarChar(MAX)")] string dF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqClient", DbType="NVarChar(MAX)")] string remarqClient, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqProjet", DbType="NVarChar(MAX)")] string remarqProjet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, description, idclient, idphace, idTypeProjet, taskforce, idclasseProjet, revision, dD, dF, remarqClient, remarqProjet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatDetailProjet")]
	public int updatDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclient, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idphace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idTypeProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string taskforce, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string idclasseProjet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Revision", DbType="NVarChar(MAX)")] string revision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DD", DbType="NVarChar(MAX)")] string dD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DF", DbType="NVarChar(MAX)")] string dF, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqClient", DbType="NVarChar(MAX)")] string remarqClient, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RemarqProjet", DbType="NVarChar(MAX)")] string remarqProjet)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, description, idclient, idphace, idTypeProjet, taskforce, idclasseProjet, revision, dD, dF, remarqClient, remarqProjet);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDetailProjet")]
	public ISingleResult<GetDetailProjetResult> GetDetailProjet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ref", DbType="NVarChar(MAX)")] string @ref)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), @ref);
		return ((ISingleResult<GetDetailProjetResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAdminByMatricule")]
	public ISingleResult<GetAdminByMatriculeResult> GetAdminByMatricule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matricule", DbType="NVarChar(MAX)")] string matricule)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matricule);
		return ((ISingleResult<GetAdminByMatriculeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertPermissionInterfaceByProj")]
	public int InsertPermissionInterfaceByProj([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matriculen", DbType="NVarChar(MAX)")] string matriculen)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reference, matriculen);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertMachineIP")]
	public int InsertMachineIP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MachineAlias", DbType="NVarChar(MAX)")] string machineAlias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MachineNom", DbType="NVarChar(MAX)")] string machineNom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MachineReference", DbType="NVarChar(MAX)")] string machineReference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP", DbType="NVarChar(MAX)")] string iP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Port", DbType="NVarChar(MAX)")] string port, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enabled", DbType="Bit")] System.Nullable<bool> enabled, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Administrateur", DbType="NVarChar(MAX)")] string administrateur)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machineAlias, machineNom, machineReference, iP, port, enabled, administrateur);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMachine")]
	public ISingleResult<GetMachineResult> GetMachine()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetMachineResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMaxDate")]
	public ISingleResult<GetMaxDateResult> GetMaxDate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MachineNumber", DbType="Int")] System.Nullable<int> machineNumber)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machineNumber);
		return ((ISingleResult<GetMaxDateResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_Contact")]
	public int Insert_Contact([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Civ", DbType="Int")] System.Nullable<int> iD_Civ, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom", DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prenom", DbType="NVarChar(MAX)")] string prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="NVarChar(MAX)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(MAX)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="E_mail", DbType="NVarChar(MAX)")] string e_mail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Fonction", DbType="Int")] System.Nullable<int> iD_Fonction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suivi_par", DbType="NVarChar(MAX)")] string suivi_par)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Civ, nom, prenom, telephone, mobile, e_mail, iD_Fonction, iD_Entreprise, suivi_par);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertEntreprise")]
	public int InsertEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom", DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="NVarChar(MAX)")] string telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adresse", DbType="NVarChar(MAX)")] string adresse, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adresse_2", DbType="NVarChar(MAX)")] string adresse_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code_postal", DbType="Int")] System.Nullable<int> code_postal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ville", DbType="NVarChar(MAX)")] string ville, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pays", DbType="NVarChar(MAX)")] string pays, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site_internet", DbType="NVarChar(MAX)")] string site_internet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Groupe", DbType="Int")] System.Nullable<int> iD_Groupe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Etat", DbType="NVarChar(MAX)")] string etat)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom, telephone, fax, adresse, adresse_2, code_postal, ville, pays, site_internet, iD_Groupe, etat);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateEntreprise")]
	public int UpdateEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom", DbType="NVarChar(MAX)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telephone", DbType="Int")] System.Nullable<int> telephone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="Int")] System.Nullable<int> fax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adresse", DbType="NVarChar(MAX)")] string adresse, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adresse_2", DbType="NVarChar(MAX)")] string adresse_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code_postal", DbType="Int")] System.Nullable<int> code_postal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ville", DbType="NVarChar(MAX)")] string ville, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pays", DbType="NVarChar(MAX)")] string pays, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Site_internet", DbType="NVarChar(MAX)")] string site_internet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Groupe", DbType="Int")] System.Nullable<int> iD_Groupe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Etat", DbType="NVarChar(MAX)")] string etat)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Entreprise, nom, telephone, fax, adresse, adresse_2, code_postal, ville, pays, site_internet, iD_Groupe, etat);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDetailEntreprise")]
	public ISingleResult<GetDetailEntrepriseResult> GetDetailEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Entreprise);
		return ((ISingleResult<GetDetailEntrepriseResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetContact")]
	public ISingleResult<GetContactResult> GetContact([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Entreprise);
		return ((ISingleResult<GetContactResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteEntreprise")]
	public int DeleteEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Entreprise);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteContact_byIDEntreprise")]
	public int DeleteContact_byIDEntreprise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Entreprise", DbType="Int")] System.Nullable<int> iD_Entreprise)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Entreprise);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertNomenclature_Evenement")]
	public int insertNomenclature_Evenement([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_TypeEv", DbType="Int")] System.Nullable<int> iD_TypeEv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Objet", DbType="NVarChar(MAX)")] string objet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateDebut", DbType="Date")] System.Nullable<System.DateTime> dateDebut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Heure", DbType="Time")] System.Nullable<System.TimeSpan> heure, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateFin", DbType="Date")] System.Nullable<System.DateTime> dateFin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HeureFin", DbType="Time")] System.Nullable<System.TimeSpan> heureFin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lieu", DbType="NVarChar(MAX)")] string lieu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescriptionEv", DbType="NVarChar(MAX)")] string descriptionEv, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Contact", DbType="Int")] System.Nullable<int> iD_Contact)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_TypeEv, objet, dateDebut, heure, dateFin, heureFin, lieu, descriptionEv, iD_Contact);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUtilisateurByEmail")]
	public ISingleResult<GetUtilisateurByEmailResult> GetUtilisateurByEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string password)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
		return ((ISingleResult<GetUtilisateurByEmailResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUtilisateur")]
	public ISingleResult<GetUtilisateurResult> GetUtilisateur()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetUtilisateurResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entreprise")]
public partial class Entreprise : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Entreprise;
	
	private string _Nom;
	
	private System.Nullable<int> _Téléphone;
	
	private System.Nullable<int> _Fax;
	
	private string _Adresse;
	
	private string _Adresse_2;
	
	private System.Nullable<int> _Code_postal;
	
	private string _Ville;
	
	private string _Pays;
	
	private string _Site_internet;
	
	private System.Nullable<int> _ID_Groupe;
	
	private string _Etat;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EntrepriseChanging(int value);
    partial void OnID_EntrepriseChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnTéléphoneChanging(System.Nullable<int> value);
    partial void OnTéléphoneChanged();
    partial void OnFaxChanging(System.Nullable<int> value);
    partial void OnFaxChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnAdresse_2Changing(string value);
    partial void OnAdresse_2Changed();
    partial void OnCode_postalChanging(System.Nullable<int> value);
    partial void OnCode_postalChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnPaysChanging(string value);
    partial void OnPaysChanged();
    partial void OnSite_internetChanging(string value);
    partial void OnSite_internetChanged();
    partial void OnID_GroupeChanging(System.Nullable<int> value);
    partial void OnID_GroupeChanged();
    partial void OnEtatChanging(string value);
    partial void OnEtatChanged();
    #endregion
	
	public Entreprise()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Entreprise", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Entreprise
	{
		get
		{
			return this._ID_Entreprise;
		}
		set
		{
			if ((this._ID_Entreprise != value))
			{
				this.OnID_EntrepriseChanging(value);
				this.SendPropertyChanging();
				this._ID_Entreprise = value;
				this.SendPropertyChanged("ID_Entreprise");
				this.OnID_EntrepriseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this.OnNomChanging(value);
				this.SendPropertyChanging();
				this._Nom = value;
				this.SendPropertyChanged("Nom");
				this.OnNomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Téléphone", DbType="Int")]
	public System.Nullable<int> Téléphone
	{
		get
		{
			return this._Téléphone;
		}
		set
		{
			if ((this._Téléphone != value))
			{
				this.OnTéléphoneChanging(value);
				this.SendPropertyChanging();
				this._Téléphone = value;
				this.SendPropertyChanged("Téléphone");
				this.OnTéléphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="Int")]
	public System.Nullable<int> Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this.OnFaxChanging(value);
				this.SendPropertyChanging();
				this._Fax = value;
				this.SendPropertyChanged("Fax");
				this.OnFaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="NVarChar(MAX)")]
	public string Adresse
	{
		get
		{
			return this._Adresse;
		}
		set
		{
			if ((this._Adresse != value))
			{
				this.OnAdresseChanging(value);
				this.SendPropertyChanging();
				this._Adresse = value;
				this.SendPropertyChanged("Adresse");
				this.OnAdresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse_2", DbType="NVarChar(MAX)")]
	public string Adresse_2
	{
		get
		{
			return this._Adresse_2;
		}
		set
		{
			if ((this._Adresse_2 != value))
			{
				this.OnAdresse_2Changing(value);
				this.SendPropertyChanging();
				this._Adresse_2 = value;
				this.SendPropertyChanged("Adresse_2");
				this.OnAdresse_2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_postal", DbType="Int")]
	public System.Nullable<int> Code_postal
	{
		get
		{
			return this._Code_postal;
		}
		set
		{
			if ((this._Code_postal != value))
			{
				this.OnCode_postalChanging(value);
				this.SendPropertyChanging();
				this._Code_postal = value;
				this.SendPropertyChanged("Code_postal");
				this.OnCode_postalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(MAX)")]
	public string Ville
	{
		get
		{
			return this._Ville;
		}
		set
		{
			if ((this._Ville != value))
			{
				this.OnVilleChanging(value);
				this.SendPropertyChanging();
				this._Ville = value;
				this.SendPropertyChanged("Ville");
				this.OnVilleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pays", DbType="NVarChar(MAX)")]
	public string Pays
	{
		get
		{
			return this._Pays;
		}
		set
		{
			if ((this._Pays != value))
			{
				this.OnPaysChanging(value);
				this.SendPropertyChanging();
				this._Pays = value;
				this.SendPropertyChanged("Pays");
				this.OnPaysChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_internet", DbType="NVarChar(MAX)")]
	public string Site_internet
	{
		get
		{
			return this._Site_internet;
		}
		set
		{
			if ((this._Site_internet != value))
			{
				this.OnSite_internetChanging(value);
				this.SendPropertyChanging();
				this._Site_internet = value;
				this.SendPropertyChanged("Site_internet");
				this.OnSite_internetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Groupe", DbType="Int")]
	public System.Nullable<int> ID_Groupe
	{
		get
		{
			return this._ID_Groupe;
		}
		set
		{
			if ((this._ID_Groupe != value))
			{
				this.OnID_GroupeChanging(value);
				this.SendPropertyChanging();
				this._ID_Groupe = value;
				this.SendPropertyChanged("ID_Groupe");
				this.OnID_GroupeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="NVarChar(MAX)")]
	public string Etat
	{
		get
		{
			return this._Etat;
		}
		set
		{
			if ((this._Etat != value))
			{
				this.OnEtatChanging(value);
				this.SendPropertyChanging();
				this._Etat = value;
				this.SendPropertyChanged("Etat");
				this.OnEtatChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nomenclature_Contact")]
public partial class Nomenclature_Contact : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Contact;
	
	private System.Nullable<int> _ID_Civ;
	
	private string _Nom;
	
	private string _Prenom;
	
	private System.Nullable<int> _Téléphone;
	
	private System.Nullable<int> _Mobile;
	
	private string _E_mail;
	
	private System.Nullable<int> _ID_Fonction;
	
	private System.Nullable<int> _ID_Entreprise;
	
	private string _Suivi_par;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ContactChanging(int value);
    partial void OnID_ContactChanged();
    partial void OnID_CivChanging(System.Nullable<int> value);
    partial void OnID_CivChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnTéléphoneChanging(System.Nullable<int> value);
    partial void OnTéléphoneChanged();
    partial void OnMobileChanging(System.Nullable<int> value);
    partial void OnMobileChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnID_FonctionChanging(System.Nullable<int> value);
    partial void OnID_FonctionChanged();
    partial void OnID_EntrepriseChanging(System.Nullable<int> value);
    partial void OnID_EntrepriseChanged();
    partial void OnSuivi_parChanging(string value);
    partial void OnSuivi_parChanged();
    #endregion
	
	public Nomenclature_Contact()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Contact", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Contact
	{
		get
		{
			return this._ID_Contact;
		}
		set
		{
			if ((this._ID_Contact != value))
			{
				this.OnID_ContactChanging(value);
				this.SendPropertyChanging();
				this._ID_Contact = value;
				this.SendPropertyChanged("ID_Contact");
				this.OnID_ContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Civ", DbType="Int")]
	public System.Nullable<int> ID_Civ
	{
		get
		{
			return this._ID_Civ;
		}
		set
		{
			if ((this._ID_Civ != value))
			{
				this.OnID_CivChanging(value);
				this.SendPropertyChanging();
				this._ID_Civ = value;
				this.SendPropertyChanged("ID_Civ");
				this.OnID_CivChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this.OnNomChanging(value);
				this.SendPropertyChanging();
				this._Nom = value;
				this.SendPropertyChanged("Nom");
				this.OnNomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(MAX)")]
	public string Prenom
	{
		get
		{
			return this._Prenom;
		}
		set
		{
			if ((this._Prenom != value))
			{
				this.OnPrenomChanging(value);
				this.SendPropertyChanging();
				this._Prenom = value;
				this.SendPropertyChanged("Prenom");
				this.OnPrenomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Téléphone", DbType="Int")]
	public System.Nullable<int> Téléphone
	{
		get
		{
			return this._Téléphone;
		}
		set
		{
			if ((this._Téléphone != value))
			{
				this.OnTéléphoneChanging(value);
				this.SendPropertyChanging();
				this._Téléphone = value;
				this.SendPropertyChanged("Téléphone");
				this.OnTéléphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="Int")]
	public System.Nullable<int> Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this.OnMobileChanging(value);
				this.SendPropertyChanging();
				this._Mobile = value;
				this.SendPropertyChanged("Mobile");
				this.OnMobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_mail", DbType="NVarChar(MAX)")]
	public string E_mail
	{
		get
		{
			return this._E_mail;
		}
		set
		{
			if ((this._E_mail != value))
			{
				this.OnE_mailChanging(value);
				this.SendPropertyChanging();
				this._E_mail = value;
				this.SendPropertyChanged("E_mail");
				this.OnE_mailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fonction", DbType="Int")]
	public System.Nullable<int> ID_Fonction
	{
		get
		{
			return this._ID_Fonction;
		}
		set
		{
			if ((this._ID_Fonction != value))
			{
				this.OnID_FonctionChanging(value);
				this.SendPropertyChanging();
				this._ID_Fonction = value;
				this.SendPropertyChanged("ID_Fonction");
				this.OnID_FonctionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Entreprise", DbType="Int")]
	public System.Nullable<int> ID_Entreprise
	{
		get
		{
			return this._ID_Entreprise;
		}
		set
		{
			if ((this._ID_Entreprise != value))
			{
				this.OnID_EntrepriseChanging(value);
				this.SendPropertyChanging();
				this._ID_Entreprise = value;
				this.SendPropertyChanged("ID_Entreprise");
				this.OnID_EntrepriseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suivi_par", DbType="NVarChar(MAX)")]
	public string Suivi_par
	{
		get
		{
			return this._Suivi_par;
		}
		set
		{
			if ((this._Suivi_par != value))
			{
				this.OnSuivi_parChanging(value);
				this.SendPropertyChanging();
				this._Suivi_par = value;
				this.SendPropertyChanged("Suivi_par");
				this.OnSuivi_parChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilisateur")]
public partial class Utilisateur : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _users;
	
	private string _Email;
	
	private string _password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusersChanging(string value);
    partial void OnusersChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
	
	public Utilisateur()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users", DbType="NVarChar(MAX)")]
	public string users
	{
		get
		{
			return this._users;
		}
		set
		{
			if ((this._users != value))
			{
				this.OnusersChanging(value);
				this.SendPropertyChanging();
				this._users = value;
				this.SendPropertyChanged("users");
				this.OnusersChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Attribut_Evenement")]
public partial class Attribut_Evenement : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _Matricule;
	
	private System.Nullable<int> _ID_Evenement;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMatriculeChanging(System.Nullable<int> value);
    partial void OnMatriculeChanged();
    partial void OnID_EvenementChanging(System.Nullable<int> value);
    partial void OnID_EvenementChanged();
    #endregion
	
	public Attribut_Evenement()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="Int")]
	public System.Nullable<int> Matricule
	{
		get
		{
			return this._Matricule;
		}
		set
		{
			if ((this._Matricule != value))
			{
				this.OnMatriculeChanging(value);
				this.SendPropertyChanging();
				this._Matricule = value;
				this.SendPropertyChanged("Matricule");
				this.OnMatriculeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Evenement", DbType="Int")]
	public System.Nullable<int> ID_Evenement
	{
		get
		{
			return this._ID_Evenement;
		}
		set
		{
			if ((this._ID_Evenement != value))
			{
				this.OnID_EvenementChanging(value);
				this.SendPropertyChanging();
				this._ID_Evenement = value;
				this.SendPropertyChanged("ID_Evenement");
				this.OnID_EvenementChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nomenclature_Evenement")]
public partial class Nomenclature_Evenement : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Evenement;
	
	private System.Nullable<int> _ID_Contact;
	
	private System.Nullable<int> _ID_TypeEv;
	
	private System.Nullable<int> _ID_Status;
	
	private string _Objet;
	
	private System.Nullable<System.DateTime> _DateDebut;
	
	private System.Nullable<System.TimeSpan> _Heure;
	
	private System.Nullable<System.DateTime> _DateFin;
	
	private System.Nullable<System.TimeSpan> _HeureFin;
	
	private string _Lieu;
	
	private string _DescriptionEv;
	
	private string _Attribue_a;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EvenementChanging(int value);
    partial void OnID_EvenementChanged();
    partial void OnID_ContactChanging(System.Nullable<int> value);
    partial void OnID_ContactChanged();
    partial void OnID_TypeEvChanging(System.Nullable<int> value);
    partial void OnID_TypeEvChanged();
    partial void OnID_StatusChanging(System.Nullable<int> value);
    partial void OnID_StatusChanged();
    partial void OnObjetChanging(string value);
    partial void OnObjetChanged();
    partial void OnDateDebutChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDebutChanged();
    partial void OnHeureChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHeureChanged();
    partial void OnDateFinChanging(System.Nullable<System.DateTime> value);
    partial void OnDateFinChanged();
    partial void OnHeureFinChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHeureFinChanged();
    partial void OnLieuChanging(string value);
    partial void OnLieuChanged();
    partial void OnDescriptionEvChanging(string value);
    partial void OnDescriptionEvChanged();
    partial void OnAttribue_aChanging(string value);
    partial void OnAttribue_aChanged();
    #endregion
	
	public Nomenclature_Evenement()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Evenement", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Evenement
	{
		get
		{
			return this._ID_Evenement;
		}
		set
		{
			if ((this._ID_Evenement != value))
			{
				this.OnID_EvenementChanging(value);
				this.SendPropertyChanging();
				this._ID_Evenement = value;
				this.SendPropertyChanged("ID_Evenement");
				this.OnID_EvenementChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Contact", DbType="Int")]
	public System.Nullable<int> ID_Contact
	{
		get
		{
			return this._ID_Contact;
		}
		set
		{
			if ((this._ID_Contact != value))
			{
				this.OnID_ContactChanging(value);
				this.SendPropertyChanging();
				this._ID_Contact = value;
				this.SendPropertyChanged("ID_Contact");
				this.OnID_ContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TypeEv", DbType="Int")]
	public System.Nullable<int> ID_TypeEv
	{
		get
		{
			return this._ID_TypeEv;
		}
		set
		{
			if ((this._ID_TypeEv != value))
			{
				this.OnID_TypeEvChanging(value);
				this.SendPropertyChanging();
				this._ID_TypeEv = value;
				this.SendPropertyChanged("ID_TypeEv");
				this.OnID_TypeEvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Status", DbType="Int")]
	public System.Nullable<int> ID_Status
	{
		get
		{
			return this._ID_Status;
		}
		set
		{
			if ((this._ID_Status != value))
			{
				this.OnID_StatusChanging(value);
				this.SendPropertyChanging();
				this._ID_Status = value;
				this.SendPropertyChanged("ID_Status");
				this.OnID_StatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objet", DbType="NVarChar(MAX)")]
	public string Objet
	{
		get
		{
			return this._Objet;
		}
		set
		{
			if ((this._Objet != value))
			{
				this.OnObjetChanging(value);
				this.SendPropertyChanging();
				this._Objet = value;
				this.SendPropertyChanged("Objet");
				this.OnObjetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDebut", DbType="Date")]
	public System.Nullable<System.DateTime> DateDebut
	{
		get
		{
			return this._DateDebut;
		}
		set
		{
			if ((this._DateDebut != value))
			{
				this.OnDateDebutChanging(value);
				this.SendPropertyChanging();
				this._DateDebut = value;
				this.SendPropertyChanged("DateDebut");
				this.OnDateDebutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heure", DbType="Time")]
	public System.Nullable<System.TimeSpan> Heure
	{
		get
		{
			return this._Heure;
		}
		set
		{
			if ((this._Heure != value))
			{
				this.OnHeureChanging(value);
				this.SendPropertyChanging();
				this._Heure = value;
				this.SendPropertyChanged("Heure");
				this.OnHeureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFin", DbType="Date")]
	public System.Nullable<System.DateTime> DateFin
	{
		get
		{
			return this._DateFin;
		}
		set
		{
			if ((this._DateFin != value))
			{
				this.OnDateFinChanging(value);
				this.SendPropertyChanging();
				this._DateFin = value;
				this.SendPropertyChanged("DateFin");
				this.OnDateFinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeureFin", DbType="Time")]
	public System.Nullable<System.TimeSpan> HeureFin
	{
		get
		{
			return this._HeureFin;
		}
		set
		{
			if ((this._HeureFin != value))
			{
				this.OnHeureFinChanging(value);
				this.SendPropertyChanging();
				this._HeureFin = value;
				this.SendPropertyChanged("HeureFin");
				this.OnHeureFinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lieu", DbType="NVarChar(MAX)")]
	public string Lieu
	{
		get
		{
			return this._Lieu;
		}
		set
		{
			if ((this._Lieu != value))
			{
				this.OnLieuChanging(value);
				this.SendPropertyChanging();
				this._Lieu = value;
				this.SendPropertyChanged("Lieu");
				this.OnLieuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescriptionEv", DbType="NVarChar(MAX)")]
	public string DescriptionEv
	{
		get
		{
			return this._DescriptionEv;
		}
		set
		{
			if ((this._DescriptionEv != value))
			{
				this.OnDescriptionEvChanging(value);
				this.SendPropertyChanging();
				this._DescriptionEv = value;
				this.SendPropertyChanged("DescriptionEv");
				this.OnDescriptionEvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attribue_a", DbType="NVarChar(MAX)")]
	public string Attribue_a
	{
		get
		{
			return this._Attribue_a;
		}
		set
		{
			if ((this._Attribue_a != value))
			{
				this.OnAttribue_aChanging(value);
				this.SendPropertyChanging();
				this._Attribue_a = value;
				this.SendPropertyChanged("Attribue_a");
				this.OnAttribue_aChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class CompteUtilisateurResult
{
	
	private int _ID;
	
	private string _NomPrenom;
	
	private string _login;
	
	private string _Password;
	
	public CompteUtilisateurResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomPrenom", DbType="NVarChar(MAX)")]
	public string NomPrenom
	{
		get
		{
			return this._NomPrenom;
		}
		set
		{
			if ((this._NomPrenom != value))
			{
				this._NomPrenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(MAX)")]
	public string login
	{
		get
		{
			return this._login;
		}
		set
		{
			if ((this._login != value))
			{
				this._login = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this._Password = value;
			}
		}
	}
}

public partial class GetDetailProjetResult
{
	
	private string _reference;
	
	private string _Description;
	
	private string _taskforce;
	
	private string _Client;
	
	private string _Classe;
	
	private string _Phase;
	
	private string _Revision;
	
	private string _Type;
	
	private System.Nullable<System.DateTime> _DD;
	
	private System.Nullable<System.DateTime> _DF;
	
	private string _RemarqClient;
	
	private string _RemarqProjet;
	
	public GetDetailProjetResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference", DbType="NVarChar(MAX)")]
	public string reference
	{
		get
		{
			return this._reference;
		}
		set
		{
			if ((this._reference != value))
			{
				this._reference = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taskforce", DbType="NVarChar(MAX)")]
	public string taskforce
	{
		get
		{
			return this._taskforce;
		}
		set
		{
			if ((this._taskforce != value))
			{
				this._taskforce = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Client", DbType="NVarChar(MAX)")]
	public string Client
	{
		get
		{
			return this._Client;
		}
		set
		{
			if ((this._Client != value))
			{
				this._Client = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classe", DbType="NVarChar(MAX)")]
	public string Classe
	{
		get
		{
			return this._Classe;
		}
		set
		{
			if ((this._Classe != value))
			{
				this._Classe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phase", DbType="NVarChar(MAX)")]
	public string Phase
	{
		get
		{
			return this._Phase;
		}
		set
		{
			if ((this._Phase != value))
			{
				this._Phase = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revision", DbType="NVarChar(MAX)")]
	public string Revision
	{
		get
		{
			return this._Revision;
		}
		set
		{
			if ((this._Revision != value))
			{
				this._Revision = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(MAX)")]
	public string Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this._Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DD", DbType="Date")]
	public System.Nullable<System.DateTime> DD
	{
		get
		{
			return this._DD;
		}
		set
		{
			if ((this._DD != value))
			{
				this._DD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DF", DbType="Date")]
	public System.Nullable<System.DateTime> DF
	{
		get
		{
			return this._DF;
		}
		set
		{
			if ((this._DF != value))
			{
				this._DF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarqClient", DbType="NVarChar(MAX)")]
	public string RemarqClient
	{
		get
		{
			return this._RemarqClient;
		}
		set
		{
			if ((this._RemarqClient != value))
			{
				this._RemarqClient = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarqProjet", DbType="NVarChar(MAX)")]
	public string RemarqProjet
	{
		get
		{
			return this._RemarqProjet;
		}
		set
		{
			if ((this._RemarqProjet != value))
			{
				this._RemarqProjet = value;
			}
		}
	}
}

public partial class GetAdminByMatriculeResult
{
	
	private string _Matricule;
	
	private string _CreatedByUserID;
	
	private System.Nullable<System.DateTime> _CreatedOnDate;
	
	public GetAdminByMatriculeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricule", DbType="NVarChar(MAX)")]
	public string Matricule
	{
		get
		{
			return this._Matricule;
		}
		set
		{
			if ((this._Matricule != value))
			{
				this._Matricule = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="NChar(10)")]
	public string CreatedByUserID
	{
		get
		{
			return this._CreatedByUserID;
		}
		set
		{
			if ((this._CreatedByUserID != value))
			{
				this._CreatedByUserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedOnDate
	{
		get
		{
			return this._CreatedOnDate;
		}
		set
		{
			if ((this._CreatedOnDate != value))
			{
				this._CreatedOnDate = value;
			}
		}
	}
}

public partial class GetMachineResult
{
	
	private int _device_id;
	
	private string _MachineAlias;
	
	private string _IP;
	
	private System.Nullable<int> _Port;
	
	public GetMachineResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_id", DbType="Int NOT NULL")]
	public int device_id
	{
		get
		{
			return this._device_id;
		}
		set
		{
			if ((this._device_id != value))
			{
				this._device_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MachineAlias", DbType="NVarChar(MAX)")]
	public string MachineAlias
	{
		get
		{
			return this._MachineAlias;
		}
		set
		{
			if ((this._MachineAlias != value))
			{
				this._MachineAlias = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="NVarChar(MAX)")]
	public string IP
	{
		get
		{
			return this._IP;
		}
		set
		{
			if ((this._IP != value))
			{
				this._IP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int")]
	public System.Nullable<int> Port
	{
		get
		{
			return this._Port;
		}
		set
		{
			if ((this._Port != value))
			{
				this._Port = value;
			}
		}
	}
}

public partial class GetMaxDateResult
{
	
	private System.Nullable<System.DateTime> _DateTimeRecord;
	
	public GetMaxDateResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeRecord", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateTimeRecord
	{
		get
		{
			return this._DateTimeRecord;
		}
		set
		{
			if ((this._DateTimeRecord != value))
			{
				this._DateTimeRecord = value;
			}
		}
	}
}

public partial class GetDetailEntrepriseResult
{
	
	private int _ID_Entreprise;
	
	private string _Nom;
	
	private System.Nullable<int> _Telephone;
	
	private System.Nullable<int> _Fax;
	
	private string _Adresse;
	
	private string _Adresse_2;
	
	private System.Nullable<int> _Code_postal;
	
	private string _Ville;
	
	private string _Pays;
	
	private string _Site_internet;
	
	private string _Etat;
	
	private string _Groupe;
	
	private System.Nullable<int> _ID_Etat;
	
	private System.Nullable<int> _ID_Groupe;
	
	public GetDetailEntrepriseResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Entreprise", DbType="Int NOT NULL")]
	public int ID_Entreprise
	{
		get
		{
			return this._ID_Entreprise;
		}
		set
		{
			if ((this._ID_Entreprise != value))
			{
				this._ID_Entreprise = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this._Nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="Int")]
	public System.Nullable<int> Telephone
	{
		get
		{
			return this._Telephone;
		}
		set
		{
			if ((this._Telephone != value))
			{
				this._Telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="Int")]
	public System.Nullable<int> Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this._Fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="NVarChar(MAX)")]
	public string Adresse
	{
		get
		{
			return this._Adresse;
		}
		set
		{
			if ((this._Adresse != value))
			{
				this._Adresse = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse_2", DbType="NVarChar(MAX)")]
	public string Adresse_2
	{
		get
		{
			return this._Adresse_2;
		}
		set
		{
			if ((this._Adresse_2 != value))
			{
				this._Adresse_2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_postal", DbType="Int")]
	public System.Nullable<int> Code_postal
	{
		get
		{
			return this._Code_postal;
		}
		set
		{
			if ((this._Code_postal != value))
			{
				this._Code_postal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(MAX)")]
	public string Ville
	{
		get
		{
			return this._Ville;
		}
		set
		{
			if ((this._Ville != value))
			{
				this._Ville = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pays", DbType="NVarChar(MAX)")]
	public string Pays
	{
		get
		{
			return this._Pays;
		}
		set
		{
			if ((this._Pays != value))
			{
				this._Pays = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_internet", DbType="NVarChar(MAX)")]
	public string Site_internet
	{
		get
		{
			return this._Site_internet;
		}
		set
		{
			if ((this._Site_internet != value))
			{
				this._Site_internet = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="NVarChar(MAX)")]
	public string Etat
	{
		get
		{
			return this._Etat;
		}
		set
		{
			if ((this._Etat != value))
			{
				this._Etat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Groupe", DbType="NVarChar(MAX)")]
	public string Groupe
	{
		get
		{
			return this._Groupe;
		}
		set
		{
			if ((this._Groupe != value))
			{
				this._Groupe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Etat", DbType="Int")]
	public System.Nullable<int> ID_Etat
	{
		get
		{
			return this._ID_Etat;
		}
		set
		{
			if ((this._ID_Etat != value))
			{
				this._ID_Etat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Groupe", DbType="Int")]
	public System.Nullable<int> ID_Groupe
	{
		get
		{
			return this._ID_Groupe;
		}
		set
		{
			if ((this._ID_Groupe != value))
			{
				this._ID_Groupe = value;
			}
		}
	}
}

public partial class GetContactResult
{
	
	private int _ID_Contact;
	
	private System.Nullable<int> _ID_Civ;
	
	private string _Nom;
	
	private string _Prenom;
	
	private string _Telephone;
	
	private string _Mobile;
	
	private string _E_mail;
	
	private System.Nullable<int> _ID_Fonction;
	
	private System.Nullable<int> _ID_Entreprise;
	
	private string _Suivi_par;
	
	public GetContactResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Contact", DbType="Int NOT NULL")]
	public int ID_Contact
	{
		get
		{
			return this._ID_Contact;
		}
		set
		{
			if ((this._ID_Contact != value))
			{
				this._ID_Contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Civ", DbType="Int")]
	public System.Nullable<int> ID_Civ
	{
		get
		{
			return this._ID_Civ;
		}
		set
		{
			if ((this._ID_Civ != value))
			{
				this._ID_Civ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="NVarChar(MAX)")]
	public string Nom
	{
		get
		{
			return this._Nom;
		}
		set
		{
			if ((this._Nom != value))
			{
				this._Nom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="NVarChar(MAX)")]
	public string Prenom
	{
		get
		{
			return this._Prenom;
		}
		set
		{
			if ((this._Prenom != value))
			{
				this._Prenom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(MAX)")]
	public string Telephone
	{
		get
		{
			return this._Telephone;
		}
		set
		{
			if ((this._Telephone != value))
			{
				this._Telephone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(MAX)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this._Mobile = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_mail", DbType="NVarChar(MAX)")]
	public string E_mail
	{
		get
		{
			return this._E_mail;
		}
		set
		{
			if ((this._E_mail != value))
			{
				this._E_mail = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Fonction", DbType="Int")]
	public System.Nullable<int> ID_Fonction
	{
		get
		{
			return this._ID_Fonction;
		}
		set
		{
			if ((this._ID_Fonction != value))
			{
				this._ID_Fonction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Entreprise", DbType="Int")]
	public System.Nullable<int> ID_Entreprise
	{
		get
		{
			return this._ID_Entreprise;
		}
		set
		{
			if ((this._ID_Entreprise != value))
			{
				this._ID_Entreprise = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suivi_par", DbType="NVarChar(MAX)")]
	public string Suivi_par
	{
		get
		{
			return this._Suivi_par;
		}
		set
		{
			if ((this._Suivi_par != value))
			{
				this._Suivi_par = value;
			}
		}
	}
}

public partial class GetUtilisateurByEmailResult
{
	
	private int _id;
	
	private string _users;
	
	private string _Email;
	
	public GetUtilisateurByEmailResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users", DbType="NVarChar(MAX)")]
	public string users
	{
		get
		{
			return this._users;
		}
		set
		{
			if ((this._users != value))
			{
				this._users = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
}

public partial class GetUtilisateurResult
{
	
	private int _id;
	
	private string _users;
	
	private string _Email;
	
	private string _password;
	
	public GetUtilisateurResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users", DbType="NVarChar(MAX)")]
	public string users
	{
		get
		{
			return this._users;
		}
		set
		{
			if ((this._users != value))
			{
				this._users = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this._password = value;
			}
		}
	}
}
#pragma warning restore 1591
